"""add_rating_and_reviews_count

Revision ID: 172027baaab5
Revises: 9b99e7443ab7
Create Date: 2026-05-13 10:55:04.626531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172027baaab5'
down_revision: Union[str, None] = '9b99e7443ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_services', sa.Column('rating', sa.Float(), server_default='4.5', nullable=False))
    op.add_column('provider_services', sa.Column('reviews_count', sa.SmallInteger(), server_default='100', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_services', 'reviews_count')
    op.drop_column('provider_services', 'rating')
    # ### end Alembic commands ###
