"""add promo codes table and booking promo columns

Revision ID: 250ad3b5fb48
Revises: d25f775aef56
Create Date: 2026-05-23 19:47:11.247299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '250ad3b5fb48'
down_revision: Union[str, None] = 'd25f775aef56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('discount_type', sa.String(length=15), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('min_booking_amount', sa.Float(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_customer', sa.SmallInteger(), nullable=False),
    sa.Column('max_discount_amount', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'code', name='uq_provider_promo_code')
    )
    op.create_index(op.f('ix_promo_codes_provider_id'), 'promo_codes', ['provider_id'], unique=False)
    op.add_column('bookings', sa.Column('promo_code_id', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('discount_amount', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('bookings', sa.Column('original_price', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'promo_codes', ['promo_code_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'original_price')
    op.drop_column('bookings', 'discount_amount')
    op.drop_column('bookings', 'promo_code_id')
    op.drop_index(op.f('ix_promo_codes_provider_id'), table_name='promo_codes')
    op.drop_table('promo_codes')
    # ### end Alembic commands ###
