"""Add verification_token

Revision ID: 92ab8b521e0c
Revises: 9f2b4d0c1a77
Create Date: 2026-04-23 17:35:15.207343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ab8b521e0c'
down_revision: Union[str, None] = '9f2b4d0c1a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_sessions', sa.Column('verification_token', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_password_reset_sessions_verification_token'), 'password_reset_sessions', ['verification_token'], unique=False)
    op.drop_index('ix_recovery_rate_limits_email', table_name='recovery_rate_limits')
    op.drop_index('ix_recovery_rate_limits_endpoint', table_name='recovery_rate_limits')
    op.drop_index('ix_recovery_rate_limits_window_start', table_name='recovery_rate_limits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_recovery_rate_limits_window_start', 'recovery_rate_limits', ['window_start'], unique=False)
    op.create_index('ix_recovery_rate_limits_endpoint', 'recovery_rate_limits', ['endpoint'], unique=False)
    op.create_index('ix_recovery_rate_limits_email', 'recovery_rate_limits', ['email'], unique=False)
    op.drop_index(op.f('ix_password_reset_sessions_verification_token'), table_name='password_reset_sessions')
    op.drop_column('password_reset_sessions', 'verification_token')
    # ### end Alembic commands ###
