"""create_reviews_table

Revision ID: d25f775aef56
Revises: d3f8a9b7c1e2
Create Date: 2026-05-22 14:21:16.644396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd25f775aef56'
down_revision: Union[str, None] = 'd3f8a9b7c1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('provider_service_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_service_id'], ['provider_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', name='uq_review_booking_id')
    )
    op.create_index('ix_reviews_customer_id', 'reviews', ['customer_id'], unique=False)
    op.create_index('ix_reviews_provider_id', 'reviews', ['provider_id'], unique=False)
    op.create_index('ix_reviews_provider_service_id', 'reviews', ['provider_service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_provider_service_id', table_name='reviews')
    op.drop_index('ix_reviews_provider_id', table_name='reviews')
    op.drop_index('ix_reviews_customer_id', table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
