"""create support and faqs tables

Revision ID: ea9f159328b8
Revises: 390a0776aae5
Create Date: 2026-05-19 14:02:39.902758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea9f159328b8'
down_revision: Union[str, None] = '390a0776aae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faqs',
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faqs_category'), 'faqs', ['category'], unique=False)
    op.create_table('privacy_policies',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Seed data
    import uuid
    faq_table = sa.table(
        'faqs',
        sa.column('id', sa.UUID),
        sa.column('question', sa.String),
        sa.column('answer', sa.Text),
        sa.column('category', sa.String),
        sa.column('is_active', sa.Boolean),
        sa.column('is_deleted', sa.Boolean),
    )
    
    privacy_table = sa.table(
        'privacy_policies',
        sa.column('id', sa.UUID),
        sa.column('title', sa.String),
        sa.column('content', sa.Text),
        sa.column('version', sa.String),
        sa.column('is_active', sa.Boolean),
    )
    
    op.bulk_insert(
        faq_table,
        [
            {
                "id": str(uuid.uuid4()),
                "question": "What is Serviko?",
                "answer": "Serviko is a premium on-demand platform connecting customers with top-tier service providers in their local area.",
                "category": "general",
                "is_active": True,
                "is_deleted": False
            },
            {
                "id": str(uuid.uuid4()),
                "question": "How do I book a service?",
                "answer": "Browse the categories, choose a service provider, select an available date and time slot and confirm your booking. The provider will then accept or coordinate with you.",
                "category": "general",
                "is_active": True,
                "is_deleted": False
            },
            {
                "id": str(uuid.uuid4()),
                "question": "How do I create a provider profile?",
                "answer": "You can sign up as a customer and submit a request to become a provider from the account profile page by uploading the required verification documents.",
                "category": "account",
                "is_active": True,
                "is_deleted": False
            },
            {
                "id": str(uuid.uuid4()),
                "question": "Can I use the same account for both customer and provider?",
                "answer": "Yes, Serviko supports a unified account system. You can switch your role seamlessly from the side navigation or profile section.",
                "category": "account",
                "is_active": True,
                "is_deleted": False
            },
            {
                "id": str(uuid.uuid4()),
                "question": "What services are available on Serviko?",
                "answer": "We offer a wide range of services including home cleaning, repair works, personal training, tutor sessions and professional consultations.",
                "category": "services",
                "is_active": True,
                "is_deleted": False
            },
            {
                "id": str(uuid.uuid4()),
                "question": "Can I cancel a booking after confirmation?",
                "answer": "Yes, you can cancel your booking from the bookings history tab. Please note that cancellations close to the scheduled start time may be subject to a cancellation policy fee.",
                "category": "services",
                "is_active": True,
                "is_deleted": False
            },
            {
                "id": str(uuid.uuid4()),
                "question": "What payment methods are supported?",
                "answer": "Serviko supports all major credit/debit cards, secure net banking and digital wallets. Payments are processed securely via our payments gateway.",
                "category": "payments",
                "is_active": True,
                "is_deleted": False
            },
            {
                "id": str(uuid.uuid4()),
                "question": "When am I charged for a booking?",
                "answer": "A temporary authorization hold may be placed upon booking. You are only fully charged once the service is completed by the provider.",
                "category": "payments",
                "is_active": True,
                "is_deleted": False
            }
        ]
    )
    
    op.bulk_insert(
        privacy_table,
        [
            {
                "id": str(uuid.uuid4()),
                "title": "Serviko Privacy Policy",
                "content": """### 1. Information We Collect
We collect information you provide directly to us when creating or modifying your account, requesting services or contacting customer support. This may include your name, email address, phone number, physical address, profile picture, payment method and service requests.

### 2. How We Use Your Information
We use the information we collect to:
* Provide, maintain, and improve our services;
* Facilitate connections between customers and service providers;
* Process payments and send receipts;
* Send updates, security alerts and administrative messages;
* Personalize and improve the services.

### 3. Sharing of Information
We may share the information we collect about you as described in this policy or at the time of collection:
* With service providers to enable them to perform the services you request;
* With the general public if you submit content in a public forum such as reviews or ratings;
* In response to a request for information by a competent authority if we believe disclosure is in accordance with applicable law;
* With law enforcement officials, government authorities or other third parties to protect the rights, property or safety of Serviko or others.

### 4. Security of Data
We take reasonable measures to protect your personal data from loss, theft, misuse, unauthorized access, disclosure, alteration, and destruction. However, no security system is impenetrable and we cannot guarantee the security of our database, nor can we guarantee that the information you supply won't be intercepted while being transmitted to us over the internet.

### 5. Your Choices and Account Information
You may update, correct or delete your account information at any time by logging into your account or contacting support. If you wish to delete your account, please email us, but note that we may retain certain information as required by law or for legitimate business purposes.

### 6. Changes to this Policy
We may change this Privacy Policy from time to time. If we make significant changes, we will notify you through the app or by other means, such as email.""",
                "version": "1.0.0",
                "is_active": True
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('privacy_policies')
    op.drop_index(op.f('ix_faqs_category'), table_name='faqs')
    op.drop_table('faqs')
    # ### end Alembic commands ###
